# Generated by Django 3.2.7 on 2021-09-21 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='database',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, verbose_name='ユーザ名')),
                ('password', models.CharField(max_length=255, verbose_name='パスワード')),
                ('answer', models.CharField(max_length=255, verbose_name='回答')),
                ('score', models.IntegerField(max_length=255, verbose_name='スコア')),
                ('course', models.IntegerField(max_length=255, verbose_name='コース')),
            ],
        ),
    ]
